# Mann Turbulence Generation Configuration File
# This file defines the parameters for generating synthetic turbulence fields using the Mann model.
# It includes stencil/grid settings, turbulence box definitions, and optional velocity constraints.
# This example generates three turbulence boxes with different spectral scaling and random seeds,
# all sharing the same Mann stencil parameters.

[stencil_params]
L = 30.0    # Length scale (m), characterizes the size of energy-containing eddies
gamma = 3.9 # Anisotropy parameter, controls the elongation of turbulence structures
Lx = 200.0 # Domain length in x-direction (m)
Ly = 200.0 # Domain length in y-direction (m)
Lz = 8192.0 # Domain length in z-direction (m)
Nx = 4028   # Number of grid points in x-direction
Ny = 32     # Number of grid points in y-direction
Nz = 32     # Number of grid points in z-direction

# Periodicity settings:
# These flags determine whether the turbulence box is periodic in each spatial direction.
# Setting a direction to periodic (false) can reduce computational cost by approximately half.
# If omitted, lateral (y) and vertical (z) axes are set to to aperiodic.
# aperiodic_x = false
# aperiodic_y = true
# aperiodic_z = true

# sinc_thres = 3.0 # Threshold for applying the Mann sinc correction to low-frequency modes (default = 3.0)

# Turbulence boxes:
# Each entry defines a separate turbulence realization with its own spectral scaling and seed.
# You can add as many turbulence boxes as needed to generate multiple outputs from the same stencil.
[[turbulence_boxes]]
ae = 0.1              # Spectral scaling factor (αε^{2/3}), controls the amplitude of the turbulence spectrum
seed = 42             # Random seed for reproducibility
output = "output1.nc" # Output file name for the generated turbulence field
# format = "netCDF"   # Output format: 'netCDF' or 'HAWC2' (default = 'netCDF')

[[turbulence_boxes]]
ae = 0.1
seed = 123
output = "output2.nc"
format = "HAWC2"

[[turbulence_boxes]]
ae = 0.1
seed = 234
output = "output3.nc"

# Constraint settings: Ommitting constraint_params will generate an
# unconstrained box. See the input_file_example_constrained.toml for an example
# of a constrained turbulence input file.
# [constraint_params]
# spectral_compression_target = 0.8 # Desired compression ratio for the constraint impulse response (default = 0.8)
# corr_thres = 0.0001               # Threshold for sparsifying the constraint correlation matrix (default = 0.0001)
# constraints = [
#     { x = 10, y = 10, z = 10, u = 0.3 }, 
#     { x = 20, y = 20, z = 20, u = 0.3 },
# ]