name: Build
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run Pytest
        run: cargo test --all-features

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          rust-toolchain: stable
          target: ${{ matrix.target }}
          command: build
          args: --release --out dist -i ${{ matrix.python-version }}

      - name: install wheel and test
        run: |
          python --version
          pip install mannrs --find-links dist --force-reinstall
          pip install pytest
          cd tests && pytest

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist

  macos:
    runs-on: macos-13
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]

    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          rust-toolchain: stable
          target: x86_64
          command: build
          args: --release --out dist -i ${{ matrix.python-version }}

      - name: install wheel and test
        run: |
          python --version
          pip install mannrs --find-links dist --force-reinstall
          pip install pytest
          cd tests && pytest

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist

  windows:
    runs-on: windows-latest
    needs: [test]
    strategy:
      matrix:
        target: [x86]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.target }}

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          rust-toolchain: stable
          target: ${{ matrix.target }}
          args: --release --out dist -i ${{ matrix.python-version }}

      - name: install wheel and test
        run: |
          python --version
          pip install mannrs --find-links dist --force-reinstall
          pip install pytest
          cd tests && pytest

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist
