name: Test & Release

on:
  push:
#     branches:
#       - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.7" # to build abi3 wheels



jobs:
  package:
    runs-on: ubuntu-18.04
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    steps:
    - uses: actions/checkout@v2
    

    - name: install maturin
      run: |
        pip3 install maturin
        pip3 show maturin
        echo "::add-path::$HOME/.local/bin"
    - name: Build wheel
      run: maturin build --release --manylinux 2014

    - uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: target/wheels/*.whl
  
