name: Test & Release

on:
  push:
#     branches:
#       - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.7" # to build abi3 wheels
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true


jobs:
  package:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target: [x86_64, i686]
    steps:
    - uses: actions/checkout@v2

    - name: install gfortran
      run: sudo apt update && sudo apt install -y gfortran

    - name: install maturin
      run: |
        pip3 install maturin
        pip3 show maturin
        echo "::add-path::$HOME/.local/bin"
    - name: Build wheel
      run: maturin build --manylinux=off --release

    - uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: target/wheels/*.whl
  
